# =========================================
# VORTEX SOCIAL PLATFORM
# ENVIRONMENT CONFIGURATION TEMPLATE
# =========================================

# App
VORTEX_APP_NAME=VORTEX
VORTEX_APP_ENV=development
VORTEX_APP_URL=http://localhost:3000

# Backend
VORTEX_API_URL=http://localhost:3000/api
VORTEX_API_VERSION=v1

# Database
DATABASE_URL=
DATABASE_NAME=vortex
DATABASE_USER=
DATABASE_PASSWORD=
DATABASE_HOST=
DATABASE_PORT=

# Authentication
AUTH_SECRET=
JWT_SECRET=
JWT_EXPIRES_IN=7d

# Google Login
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=

# Email
EMAIL_HOST=
EMAIL_PORT=
EMAIL_USER=
EMAIL_PASSWORD=
EMAIL_FROM=

# Storage
STORAGE_PROVIDER=
STORAGE_BUCKET=
STORAGE_REGION=
STORAGE_ACCESS_KEY=
STORAGE_SECRET_KEY=

# Payments
PAYMENT_PROVIDER=
PAYMENT_PUBLIC_KEY=
PAYMENT_SECRET_KEY=
PAYMENT_WEBHOOK_SECRET=

# Creator Monetization
CREATOR_PLATFORM_FEE=0.10
MINIMUM_PAYOUT=10

# VORTEX AI
AI_PROVIDER=
AI_API_KEY=
AI_MODEL=

# Notifications
PUSH_PUBLIC_KEY=
PUSH_PRIVATE_KEY=

# Analytics
ANALYTICS_ENABLED=true
ANALYTICS_PROVIDER=
ANALYTICS_KEY=

# Security
CORS_ORIGIN=http://localhost:3000
RATE_LIMIT_ENABLED=true

# Social Features
ENABLE_REELS=true
ENABLE_MARKETPLACE=true
ENABLE_GROUPS=true
ENABLE_EVENTS=true
ENABLE_GAMES=true
ENABLE_CREATOR_MONETIZATION=true
ENABLE_PREMIUM_CONTENT=true

# Upload Limits
MAX_IMAGE_SIZE_MB=10
MAX_VIDEO_SIZE_MB=100
MAX_FILE_SIZE_MB=25

# Development
DEBUG=true
LOG_LEVEL=info
